# Generated by Django 6.1.1 on 2026-10-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('GENERADA', 'Generada'), ('PAGADA', 'Pagada'), ('CONDONADA', 'Condonada')], max_length=10, verbose_name='Acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Historial de multa',
                'verbose_name_plural': 'Historial de multas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('CONDONADA', 'Condonada')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
