# Generated by Django 6.1.1 on 2026-10-08 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('nacionalidad', models.CharField(blank=True, max_length=100, verbose_name='Nacionalidad')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografía')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('sinopsis', models.TextField(blank=True, verbose_name='Sinopsis')),
                ('anio_publicacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de publicación')),
                ('portada_url', models.URLField(blank=True, verbose_name='URL de portada')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autores', models.ManyToManyField(related_name='libros', to='catalogo.autor', verbose_name='Autores')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='catalogo.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(max_length=50, unique=True, verbose_name='Código de inventario')),
                ('ubicacion_estante', models.CharField(blank=True, max_length=100, verbose_name='Ubicación en estante')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('RESERVADO', 'Reservado'), ('MANTENIMIENTO', 'En mantenimiento'), ('EXTRAVIADO', 'Extraviado')], default='DISPONIBLE', max_length=15, verbose_name='Estado')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='catalogo.libro', verbose_name='Libro')),
            ],
            options={
                'verbose_name': 'Ejemplar',
                'verbose_name_plural': 'Ejemplares',
            },
        ),
    ]
